
//TESTS FOR PROJECT APIS

GET http://127.0.0.1:3001/projects
###
GET http://127.0.0.1:3001/projects/1
###
GET http://127.0.0.1:3001/projects/filtered
Content-Type: application/json

{
    "pl_id": "1",
    "u_expected_salary": "0",
    "u_Country": "Au",
    "u_full_time": "1",
    "u_zip_code": "1160",
    "u_timezone(user)": "ME",
    "co_startdate": "",
    "co_enddate": "",
    "i_degree": "DI"
}

###
DELETE http://127.0.0.1:3001/projects/1
###

//New Project with all fields
POST http://127.0.0.1:3001/projects 
Content-Type: application/json

{
    "p_name": "testitestitesti",
    "p_maxsize": "7",
    "p_drivelink": "www.google.at",
    "p_language": "English",
    "u_userid": "1",
    "p_description": "yee"
}

###
DELETE http://127.0.0.1:3001/projets/1

###
PATCH http://127.0.0.1:3001/projects/1
Content-Type: application/json

{
    "p_maxsize": "10",
    "p_language": "Deutsch"
}

//TESTS FOR USER APIS